package com.centraldungeon.common.model;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import java.time.LocalDateTime;
import org.jspecify.annotations.Nullable;

/**
 * What every entity with its own identity shares: a string id and the two timestamps
 * (arquitectura.md 2.2).
 *
 * <p>Bridge tables with a composite key do <b>not</b> extend this - they have no id of their own and
 * no {@code updated_at} column.
 *
 * <p>The id is a UUID v7 generated by the application ({@link IdGenerator}), not by the database.
 * The old project generated ids with a stored procedure that was never versioned, so the application
 * depended on a database object that did not exist in its own schema dump (arquitectura.md 5).
 */
@MappedSuperclass
public abstract class BaseEntity {

    /** UUID v7, assigned on persist. Nullable only in the window before the entity is saved. */
    @Id
    @Column(length = 64)
    private @Nullable String id;

    /** When the row was inserted. Stamped on persist and never touched again. */
    @Column(name = "created_at", nullable = false)
    private @Nullable LocalDateTime createdAt;

    /** When the row last changed. Null until the first update. */
    @Column(name = "updated_at")
    private @Nullable LocalDateTime updatedAt;

    /**
     * Assigns the id and stamps {@code createdAt} on insert. Called by JPA, never by application
     * code. An id already set is respected, which is what lets seed data use fixed literals.
     */
    @PrePersist
    protected void onCreate() {
        if (id == null) {
            id = IdGenerator.newId();
        }
        createdAt = LocalDateTime.now();
    }

    /** Stamps {@code updatedAt} on every update. Called by JPA, never by application code. */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    /**
     * Returns the entity's id.
     *
     * <p>Non-null in its return type on purpose: everywhere in the application that asks for an id,
     * the entity is already persisted, and making every caller null-check would spread a concern
     * that only exists for a few instructions inside a service.
     *
     * @return the id
     * @throws IllegalStateException if called before the entity was persisted - a bug in the caller,
     *                               not a state the rest of the code should handle
     */
    public String getId() {
        if (id == null) {
            throw new IllegalStateException("Entity id is not assigned yet - it is set on persist");
        }
        return id;
    }

    /**
     * Returns when the row was inserted.
     *
     * @return the creation timestamp
     * @throws IllegalStateException if called before the entity was persisted
     */
    public LocalDateTime getCreatedAt() {
        if (createdAt == null) {
            throw new IllegalStateException("Entity createdAt is not assigned yet - it is set on persist");
        }
        return createdAt;
    }

    /**
     * Returns when the row last changed.
     *
     * @return the update timestamp, or null if the row was never updated
     */
    public @Nullable LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
}
